
FROM ubuntu/python:3.12-24.04_stable

ENV POETRY_HOME=/opt/poetry


RUN pip install --upgrade pip && \
    pip install poetry

WORKDIR /app

COPY pyproject.toml poetry.lock* /app/

RUN poetry install

RUN playwright install --with-deps

EXPOSE 8000

CMD ["poetry", "run", "start"]